version: "3.8"

services:
  proxy:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./packages/nginx-config/nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 80:80

  mysql:
    image: mysql:latest
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
     MYSQL_ROOT_PASSWORD: root_pass
     MYSQL_PASSWORD: dev_pass
     MYSQL_USER: dev_user
     MYSQL_DATABASE: api
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning
    volumes: 
      - redis_data:/data
    ports:
      - '6379:6379'

volumes:
  mysql_data:
  redis_data:

