/* tslint:disable */
/* eslint-disable */
/**
 * oscar-ox api
 * API description
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface AuthEntity
 */
export interface AuthEntity {
    /**
     * 
     * @type {string}
     * @memberof AuthEntity
     */
    'accessToken': string;
    /**
     * 
     * @type {string}
     * @memberof AuthEntity
     */
    'refreshToken': string;
}
/**
 * 
 * @export
 * @interface CreateProductionDto
 */
export interface CreateProductionDto {
    /**
     * 
     * @type {string}
     * @memberof CreateProductionDto
     */
    'name': string;
}
/**
 * 
 * @export
 * @interface EmailLoginAuthDto
 */
export interface EmailLoginAuthDto {
    /**
     * 
     * @type {string}
     * @memberof EmailLoginAuthDto
     */
    'email': string;
}
/**
 * 
 * @export
 * @interface EmailRegisterAuthDto
 */
export interface EmailRegisterAuthDto {
    /**
     * 
     * @type {string}
     * @memberof EmailRegisterAuthDto
     */
    'firstName': string;
    /**
     * 
     * @type {string}
     * @memberof EmailRegisterAuthDto
     */
    'lastName': string;
}
/**
 * 
 * @export
 * @interface EmailStartAuthDto
 */
export interface EmailStartAuthDto {
    /**
     * 
     * @type {string}
     * @memberof EmailStartAuthDto
     */
    'email': string;
}
/**
 * 
 * @export
 * @interface ErrorEntity
 */
export interface ErrorEntity {
    /**
     * 
     * @type {Array<string>}
     * @memberof ErrorEntity
     */
    'message': Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ErrorEntity
     */
    'statusCode': number;
}
/**
 * 
 * @export
 * @interface LocalLoginAuthDto
 */
export interface LocalLoginAuthDto {
    /**
     * 
     * @type {string}
     * @memberof LocalLoginAuthDto
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof LocalLoginAuthDto
     */
    'password': string;
}
/**
 * 
 * @export
 * @interface LocalRegisterAuthDto
 */
export interface LocalRegisterAuthDto {
    /**
     * 
     * @type {string}
     * @memberof LocalRegisterAuthDto
     */
    'firstName': string;
    /**
     * 
     * @type {string}
     * @memberof LocalRegisterAuthDto
     */
    'lastName': string;
    /**
     * 
     * @type {string}
     * @memberof LocalRegisterAuthDto
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof LocalRegisterAuthDto
     */
    'password': string;
}
/**
 * 
 * @export
 * @interface ProductionEntity
 */
export interface ProductionEntity {
    /**
     * 
     * @type {string}
     * @memberof ProductionEntity
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof ProductionEntity
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof ProductionEntity
     */
    'updatedAt': string;
    /**
     * 
     * @type {string}
     * @memberof ProductionEntity
     */
    'name': string;
}
/**
 * 
 * @export
 * @interface UpdateProductionDto
 */
export interface UpdateProductionDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateProductionDto
     */
    'name'?: string;
}
/**
 * 
 * @export
 * @interface UserEntity
 */
export interface UserEntity {
    /**
     * 
     * @type {string}
     * @memberof UserEntity
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof UserEntity
     */
    'email': string;
}

/**
 * AuthApi - axios parameter creator
 * @export
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {EmailLoginAuthDto} emailLoginAuthDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authControllerEmailLogin: async (emailLoginAuthDto: EmailLoginAuthDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'emailLoginAuthDto' is not null or undefined
            assertParamExists('authControllerEmailLogin', 'emailLoginAuthDto', emailLoginAuthDto)
            const localVarPath = `/auth/email/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(emailLoginAuthDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {EmailRegisterAuthDto} emailRegisterAuthDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authControllerEmailRegister: async (emailRegisterAuthDto: EmailRegisterAuthDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'emailRegisterAuthDto' is not null or undefined
            assertParamExists('authControllerEmailRegister', 'emailRegisterAuthDto', emailRegisterAuthDto)
            const localVarPath = `/auth/email/register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(emailRegisterAuthDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {EmailStartAuthDto} emailStartAuthDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authControllerEmailStart: async (emailStartAuthDto: EmailStartAuthDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'emailStartAuthDto' is not null or undefined
            assertParamExists('authControllerEmailStart', 'emailStartAuthDto', emailStartAuthDto)
            const localVarPath = `/auth/email/start`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(emailStartAuthDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authControllerEmailVerify: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/email/verify`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {LocalLoginAuthDto} localLoginAuthDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authControllerLocalLogin: async (localLoginAuthDto: LocalLoginAuthDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'localLoginAuthDto' is not null or undefined
            assertParamExists('authControllerLocalLogin', 'localLoginAuthDto', localLoginAuthDto)
            const localVarPath = `/auth/local/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(localLoginAuthDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {LocalRegisterAuthDto} localRegisterAuthDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authControllerLocalRegister: async (localRegisterAuthDto: LocalRegisterAuthDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'localRegisterAuthDto' is not null or undefined
            assertParamExists('authControllerLocalRegister', 'localRegisterAuthDto', localRegisterAuthDto)
            const localVarPath = `/auth/local/register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(localRegisterAuthDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authControllerLogout: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/logout`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication cookie required


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authControllerRefresh: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/refresh`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication cookie required


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 * @export
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {EmailLoginAuthDto} emailLoginAuthDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authControllerEmailLogin(emailLoginAuthDto: EmailLoginAuthDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authControllerEmailLogin(emailLoginAuthDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {EmailRegisterAuthDto} emailRegisterAuthDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authControllerEmailRegister(emailRegisterAuthDto: EmailRegisterAuthDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authControllerEmailRegister(emailRegisterAuthDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {EmailStartAuthDto} emailStartAuthDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authControllerEmailStart(emailStartAuthDto: EmailStartAuthDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authControllerEmailStart(emailStartAuthDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authControllerEmailVerify(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authControllerEmailVerify(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {LocalLoginAuthDto} localLoginAuthDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authControllerLocalLogin(localLoginAuthDto: LocalLoginAuthDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authControllerLocalLogin(localLoginAuthDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {LocalRegisterAuthDto} localRegisterAuthDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authControllerLocalRegister(localRegisterAuthDto: LocalRegisterAuthDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authControllerLocalRegister(localRegisterAuthDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authControllerLogout(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authControllerLogout(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authControllerRefresh(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authControllerRefresh(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * AuthApi - factory interface
 * @export
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * 
         * @param {EmailLoginAuthDto} emailLoginAuthDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authControllerEmailLogin(emailLoginAuthDto: EmailLoginAuthDto, options?: any): AxiosPromise<UserEntity> {
            return localVarFp.authControllerEmailLogin(emailLoginAuthDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {EmailRegisterAuthDto} emailRegisterAuthDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authControllerEmailRegister(emailRegisterAuthDto: EmailRegisterAuthDto, options?: any): AxiosPromise<AuthEntity> {
            return localVarFp.authControllerEmailRegister(emailRegisterAuthDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {EmailStartAuthDto} emailStartAuthDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authControllerEmailStart(emailStartAuthDto: EmailStartAuthDto, options?: any): AxiosPromise<UserEntity> {
            return localVarFp.authControllerEmailStart(emailStartAuthDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authControllerEmailVerify(options?: any): AxiosPromise<AuthEntity> {
            return localVarFp.authControllerEmailVerify(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {LocalLoginAuthDto} localLoginAuthDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authControllerLocalLogin(localLoginAuthDto: LocalLoginAuthDto, options?: any): AxiosPromise<AuthEntity> {
            return localVarFp.authControllerLocalLogin(localLoginAuthDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {LocalRegisterAuthDto} localRegisterAuthDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authControllerLocalRegister(localRegisterAuthDto: LocalRegisterAuthDto, options?: any): AxiosPromise<AuthEntity> {
            return localVarFp.authControllerLocalRegister(localRegisterAuthDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authControllerLogout(options?: any): AxiosPromise<void> {
            return localVarFp.authControllerLogout(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authControllerRefresh(options?: any): AxiosPromise<AuthEntity> {
            return localVarFp.authControllerRefresh(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export class AuthApi extends BaseAPI {
    /**
     * 
     * @param {EmailLoginAuthDto} emailLoginAuthDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authControllerEmailLogin(emailLoginAuthDto: EmailLoginAuthDto, options?: AxiosRequestConfig) {
        return AuthApiFp(this.configuration).authControllerEmailLogin(emailLoginAuthDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {EmailRegisterAuthDto} emailRegisterAuthDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authControllerEmailRegister(emailRegisterAuthDto: EmailRegisterAuthDto, options?: AxiosRequestConfig) {
        return AuthApiFp(this.configuration).authControllerEmailRegister(emailRegisterAuthDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {EmailStartAuthDto} emailStartAuthDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authControllerEmailStart(emailStartAuthDto: EmailStartAuthDto, options?: AxiosRequestConfig) {
        return AuthApiFp(this.configuration).authControllerEmailStart(emailStartAuthDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authControllerEmailVerify(options?: AxiosRequestConfig) {
        return AuthApiFp(this.configuration).authControllerEmailVerify(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {LocalLoginAuthDto} localLoginAuthDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authControllerLocalLogin(localLoginAuthDto: LocalLoginAuthDto, options?: AxiosRequestConfig) {
        return AuthApiFp(this.configuration).authControllerLocalLogin(localLoginAuthDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {LocalRegisterAuthDto} localRegisterAuthDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authControllerLocalRegister(localRegisterAuthDto: LocalRegisterAuthDto, options?: AxiosRequestConfig) {
        return AuthApiFp(this.configuration).authControllerLocalRegister(localRegisterAuthDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authControllerLogout(options?: AxiosRequestConfig) {
        return AuthApiFp(this.configuration).authControllerLogout(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authControllerRefresh(options?: AxiosRequestConfig) {
        return AuthApiFp(this.configuration).authControllerRefresh(options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appControllerGetHello: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async appControllerGetHello(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.appControllerGetHello(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appControllerGetHello(options?: any): AxiosPromise<void> {
            return localVarFp.appControllerGetHello(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public appControllerGetHello(options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).appControllerGetHello(options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * ProductionsApi - axios parameter creator
 * @export
 */
export const ProductionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {CreateProductionDto} createProductionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productionsControllerCreate: async (createProductionDto: CreateProductionDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createProductionDto' is not null or undefined
            assertParamExists('productionsControllerCreate', 'createProductionDto', createProductionDto)
            const localVarPath = `/productions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createProductionDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productionsControllerFindAll: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/productions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productionsControllerFindOne: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('productionsControllerFindOne', 'id', id)
            const localVarPath = `/productions/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productionsControllerRemove: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('productionsControllerRemove', 'id', id)
            const localVarPath = `/productions/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {UpdateProductionDto} updateProductionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productionsControllerUpdate: async (id: string, updateProductionDto: UpdateProductionDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('productionsControllerUpdate', 'id', id)
            // verify required parameter 'updateProductionDto' is not null or undefined
            assertParamExists('productionsControllerUpdate', 'updateProductionDto', updateProductionDto)
            const localVarPath = `/productions/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateProductionDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProductionsApi - functional programming interface
 * @export
 */
export const ProductionsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ProductionsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {CreateProductionDto} createProductionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async productionsControllerCreate(createProductionDto: CreateProductionDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProductionEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.productionsControllerCreate(createProductionDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async productionsControllerFindAll(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ProductionEntity>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.productionsControllerFindAll(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async productionsControllerFindOne(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ProductionEntity>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.productionsControllerFindOne(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async productionsControllerRemove(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ProductionEntity>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.productionsControllerRemove(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} id 
         * @param {UpdateProductionDto} updateProductionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async productionsControllerUpdate(id: string, updateProductionDto: UpdateProductionDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProductionEntity>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.productionsControllerUpdate(id, updateProductionDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ProductionsApi - factory interface
 * @export
 */
export const ProductionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ProductionsApiFp(configuration)
    return {
        /**
         * 
         * @param {CreateProductionDto} createProductionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productionsControllerCreate(createProductionDto: CreateProductionDto, options?: any): AxiosPromise<ProductionEntity> {
            return localVarFp.productionsControllerCreate(createProductionDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productionsControllerFindAll(options?: any): AxiosPromise<Array<ProductionEntity>> {
            return localVarFp.productionsControllerFindAll(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productionsControllerFindOne(id: string, options?: any): AxiosPromise<Array<ProductionEntity>> {
            return localVarFp.productionsControllerFindOne(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productionsControllerRemove(id: string, options?: any): AxiosPromise<Array<ProductionEntity>> {
            return localVarFp.productionsControllerRemove(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {UpdateProductionDto} updateProductionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productionsControllerUpdate(id: string, updateProductionDto: UpdateProductionDto, options?: any): AxiosPromise<ProductionEntity> {
            return localVarFp.productionsControllerUpdate(id, updateProductionDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ProductionsApi - object-oriented interface
 * @export
 * @class ProductionsApi
 * @extends {BaseAPI}
 */
export class ProductionsApi extends BaseAPI {
    /**
     * 
     * @param {CreateProductionDto} createProductionDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductionsApi
     */
    public productionsControllerCreate(createProductionDto: CreateProductionDto, options?: AxiosRequestConfig) {
        return ProductionsApiFp(this.configuration).productionsControllerCreate(createProductionDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductionsApi
     */
    public productionsControllerFindAll(options?: AxiosRequestConfig) {
        return ProductionsApiFp(this.configuration).productionsControllerFindAll(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductionsApi
     */
    public productionsControllerFindOne(id: string, options?: AxiosRequestConfig) {
        return ProductionsApiFp(this.configuration).productionsControllerFindOne(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductionsApi
     */
    public productionsControllerRemove(id: string, options?: AxiosRequestConfig) {
        return ProductionsApiFp(this.configuration).productionsControllerRemove(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {UpdateProductionDto} updateProductionDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductionsApi
     */
    public productionsControllerUpdate(id: string, updateProductionDto: UpdateProductionDto, options?: AxiosRequestConfig) {
        return ProductionsApiFp(this.configuration).productionsControllerUpdate(id, updateProductionDto, options).then((request) => request(this.axios, this.basePath));
    }
}


