service: oscar-ox-api

useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1
  memorySize: 256
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 'ses:SendBulkTemplatedEmail'
            - 'ses:SendEmail'
            - 'ses:SendRawEmail'
            - 'ses:SendTemplatedEmail'
          Resource: '*'

plugins:
  - serverless-offline
  - serverless-stage-manager
  - serverless-plugin-optimize
  - serverless-plugin-monorepo
  - serverless-domain-manager

package:
  exclude:
    - .git/**
    - src/**
    - test/**
    - e2e/**
    - nodemon.json
    - README.md

custom:
  stages:
    - dev
    - testing
    - prod
  domainName:
    dev: api.dev.ox.nathanrignall.uk
    testing: api.testing.ox.nathanrignall.uk
    prod: api.ox.nathanrignall.uk
  customDomain:
    domainName: ${self:custom.domainName.${sls:stage}}
    basePath: ''
    stage: ${sls:stage}
    createRoute53Record: true

functions:
  index:
    handler: dist/lambda.handler
    environment:
      DATABASE_URL: ${env:DATABASE_URL}
      JWT_SECRET: ${env:JWT_SECRET}
      JWT_REFRESH_SECRET: ${env:JWT_REFRESH_SECRET}
      JWT_EMAIL_REGISTER_SECRET: ${env:JWT_EMAIL_REGISTER_SECRET}
      JWT_EMAIL_VERIFY_SECRET: ${env:JWT_EMAIL_VERIFY_SECRET}
    events:
    - http:
        cors: true
        path: '/'
        method: any
    - http:
        cors: true
        path: '{proxy+}'
        method: any    