service: serverless-nestjs

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1

plugins:
  - serverless-offline
  - serverless-plugin-optimize
  - serverless-plugin-monorepo

package:
  exclude:
    - .git/**
    - src/**
    - test/**
    - e2e/**
    - nodemon.json
    - README.md

functions:
  index:
    handler: dist/lambda.handler
    environment:
      DATABASE_URL: ${env:DATABASE_URL}
      JWT_SECRET: ${env:JWT_SECRET}
      JWT_REFRESH_SECRET: ${env:JWT_REFRESH_SECRET}
    events:
    - http:
        cors: true
        path: '/'
        method: any
    - http:
        cors: true
        path: '{proxy+}'
        method: any