name: Deploy API Dev

on:
  push:
    branches: [dev]
    paths:
      - "apps/api/**"

  workflow_dispatch:

jobs:
  deploy:
    name: deploy
    runs-on: self-hosted
    environment: dev
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: npx nps prepare.ci.api

    - name: Build
      run: npx nps build.ci.api

    - name: Serverless
      uses: serverless/github-action@v3.1
      with:
        args: -c "cd ./apps/api && serverless deploy --stage dev"
        entrypoint: /bin/sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
