name: Deploy Web Dev

on:
  push:
    branches: [dev]
    paths:
      - "apps/web/**"

  workflow_dispatch:

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: cd ./apps/web && npm i

    - name: Install check 1
      run : ls ./apps/web
      
    - name: Install check 2
      run : ls ./apps/web/node_modules

    - name: Serverless
      uses: serverless/github-action@v1.83.3
      with:
        args: -c "cd ./apps/web && serverless"
        entrypoint: /bin/sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
